# Build the NextJS front end
FROM node:21.4.0
WORKDIR /app

COPY package*.json .
RUN npm install --legacy-peer-deps --loglevel verbose

COPY ./components ./components/
COPY ./pages ./pages/
COPY ./public ./public/
COPY ./styles ./styles/
COPY loader.js .
COPY next-env.d.ts .
COPY next.config.js .
COPY tsconfig.json .
COPY middleware.ts .

EXPOSE 3000

CMD ["npm", "run", "start"]